---
- name: Configure Jira demo host
  hosts: jira
  become: true
  vars:
    ansible_user: "{{ ansible_user | default('ansible') }}"
  roles:
    - role: common
    - role: java
    - role: postgres
    - role: jira
    - role: tls
